### ISSUE TITLE
Patch framework for Android 13

### ISSUE THREAD

**Issue by TenSeventy7** [FreshROMs/fresh#33]
**It's that time again!** Migrate framework patches to SESL 14.

- [ ] Secure Folder patches
- [ ] Knox patches for Private Share
- [x] Patches for Fresh's 'Performance Mode' presets
- [ ] Biometric framework patches for Fresh custom fingerprint animation
- [ ] Biometric framework patches for device cutout
- [x] SystemUI patches for device cutout
- [ ] Settings patches for Fresh's Software Update service

**Comment by TenSeventy7** [comment]
A significant amount of these are now impossible to patch, largely due to an AOSP change on 13.x that enforces signature verification for apps targeting R+.

Re, https://github.com/FreshROMs/Fresh/issues/44:
> We couldn't just patch the APEX as there's a signature check on first boot that would lead to the system being unbootable for 'clean flashes'.

This applies to system apps and frameworks as well.

**Comment by yassrmohmd** [comment]
![Image](https://github.com/FreshROMs/Fresh/assets/137466959/e43304c1-eb73-49f2-9835-051c924338a9)
